<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Enums\**" />
    <Compile Remove="Extensions\**" />
    <Compile Remove="Models\**" />
    <Compile Remove="Settings\**" />
    <Compile Remove="Validations\**" />
    <EmbeddedResource Remove="Enums\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <EmbeddedResource Remove="Models\**" />
    <EmbeddedResource Remove="Settings\**" />
    <EmbeddedResource Remove="Validations\**" />
    <None Remove="Enums\**" />
    <None Remove="Extensions\**" />
    <None Remove="Models\**" />
    <None Remove="Settings\**" />
    <None Remove="Validations\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entities\StudySession\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" />
    <PackageReference Include="FluentResults.Extensions.AspNetCore" />
    <PackageReference Include="FluentResults.Extensions.FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\studyRats.Service.Platform.Facade\studyRats.Service.Platform.Facade.csproj" />
  </ItemGroup>

</Project>
